version: '3'
services:
  yansan-db-mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./yansan-db/mongo/data:/data/db
  yansan-crawler:
    image: u0326/yansan-crawler:${TAG}
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    links:
      - 'yansan-db-mongo'
  yansan-web:
    image: u0326/yansan-web:${TAG}
    expose:
      - 80
    command: sh ./assets/docker_bootstrap.sh --production
    environment:
      VIRTUAL_HOST: yansan-navi.garaku.work
    links:
      - 'yansan-db-mongo'

networks:
  default:
    external:
      name: proxy_link
