version: '3'
services:
  yansan-db-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./yansan-db/mongo/data:/data/db
  yansan-crawler:
    build: './yansan-crawler'
    links:
      - 'yansan-db-mongo'
  yansan-web:
    build: './yansan-web'
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: yansan-navi.garaku.work
    links:
      - 'yansan-db-mongo'

